CHARTMETRIC_PROTOCOL = "https"
CHARTMETRIC_API_DOMAIN = "api.chartmetric.com/api"
CHARTMETRIC_API_URL = CHARTMETRIC_PROTOCOL + "://" + CHARTMETRIC_API_DOMAIN


CHARTMETRIC_API_ARTIST_ENDPOINT = "artist"
CHARTMETRIC_API_ARTIST_URL = CHARTMETRIC_API_URL + "/" + CHARTMETRIC_API_ARTIST_ENDPOINT


CHARTMETRIC_API_TRACK_ENDPOINT = "track"
CHARTMETRIC_API_TRACK_URL = CHARTMETRIC_API_URL + "/" + CHARTMETRIC_API_TRACK_ENDPOINT

CHARTMETRIC_API_TOKEN_ENDPOINT = "token"
CHARTMETRIC_API_TOKEN_URL = CHARTMETRIC_API_URL + "/" + CHARTMETRIC_API_TOKEN_ENDPOINT


CHARTMETRIC_API_ARTIST_METADATA_URL = lambda artist_id: (  
    CHARTMETRIC_API_ARTIST_URL + "/" + str(artist_id)
)
CHARTMETRIC_API_TRACK_SP_STREAMS_DAY_BY_DAY_URL = lambda track_id: (
    CHARTMETRIC_API_TRACK_URL + "/" + str(track_id) + "/spotify/stats/most-history"
)
CHARTMETRIC_API_TRACK_METADATA_URL = lambda track_id: (
    CHARTMETRIC_API_TRACK_URL + "/" + str(track_id)
)

CHARTMETRIC_API_ARTIST_SP_STREAMS__URL = lambda artist_id: (
    CHARTMETRIC_API_ARTIST_URL + "/" + str(artist_id) + "/stat/spotify"
)
CHARTMETRIC_API_ARTIST_WHERE_PEOPLE_LISTEN_URL = lambda artist_id: (
    CHARTMETRIC_API_ARTIST_URL + "/" + str(artist_id) + "/where-people-listen"
)